pw_progres_sies_home:
    path:     /progressies/accueil
    defaults:
        _controller: PWProgresSiesBundle:ProgresSies:index

pw_progres_sies_view:
    path:     /progressies/series/{id}/{choice}/{saisonid}
    defaults:
        _controller: PWProgresSiesBundle:ProgresSies:view
        choice:      0
        saisonid:    0

pw_progres_sies_view_saison:
    path:     /progressies/saison/{id}
    defaults:
        _controller: PWProgresSiesBundle:ProgresSies:viewsaison

pw_progres_sies_viewall:
    path:     /progressies/mes_series/{page}
    defaults:
        _controller: PWProgresSiesBundle:ProgresSies:viewall
        page:       1
pw_progres_sies_update:
    path:     /progressies/update/{id}/{choice}/{saisonid}
    defaults:
        _controller: PWProgresSiesBundle:ProgresSies:update
        choice:      0
        saisonid:    0

pw_progres_sies_delete:
    path:     /progressies/delete/{id}
    defaults:
        _controller: PWProgresSiesBundle:ProgresSies:delete

pw_progres_sies_add:
    path:     /progressies/add
    defaults:
        _controller: PWProgresSiesBundle:ProgresSies:add