pw_progres_sies_home:
    path:     /progressies/accueil
    defaults:
        _controller: PWProgresSiesBundle:ProgresSies:index

pw_progres_sies_view:
    path:     /progressies/series/{id}
    defaults:
        _controller: PWProgresSiesBundle:ProgresSies:view

pw_progres_sies_viewall:
    path:     /progressies/mes_series
    defaults:
        _controller: PWProgresSiesBundle:ProgresSies:viewall

pw_progres_sies_update:
    path:     /progressies/update/{id}
    defaults:
        _controller: PWProgresSiesBundle:ProgresSies:update

pw_progres_sies_delete:
    path:     /progressies/delete/{id}
    defaults:
        _controller: PWProgresSiesBundle:ProgresSies:delete

pw_progres_sies_add:
    path:     /progressies/add
    defaults:
        _controller: PWProgresSiesBundle:ProgresSies:add