pw_progres_sies_home:
    path:     /
    defaults:
        _controller: PWProgresSiesBundle:ProgresSies:index

pw_progres_sies_view:
    path:     /series/{id}/{choice}/{saisonid}
    defaults:
        _controller: PWProgresSiesBundle:ProgresSies:view
        choice:      0
        saisonid:    0

pw_progres_sies_view_saison:
    path:     /saison/{id}
    defaults:
        _controller: PWProgresSiesBundle:ProgresSies:viewsaison

pw_progres_sies_viewall:
    path:     /mes_series/{page}
    defaults:
        _controller: PWProgresSiesBundle:ProgresSies:viewall
        page:       1
pw_progres_sies_update:
    path:     /update/{id}/{choice}/{saisonid}
    defaults:
        _controller: PWProgresSiesBundle:ProgresSies:update
        choice:      0
        saisonid:    0

pw_progres_sies_delete:
    path:     /delete/{id}
    defaults:
        _controller: PWProgresSiesBundle:ProgresSies:delete

pw_progres_sies_add:
    path:     /add
    defaults:
        _controller: PWProgresSiesBundle:ProgresSies:add